#ifndef INKCELL_EMOJI_H
#define INKCELL_EMOJI_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Colour emoji sprites for the framebuffer backend.
 *
 * Meshtastic names are written by people, and on a real mesh a good share of nodes are named
 * entirely in emoji - `User.short_name` is `char[5]`, which holds exactly one. Without these a
 * node like that draws as a row of replacement boxes and cannot be told apart from any other.
 *
 * The data is generated by scripts/gen-emoji.py from Noto Color Emoji and committed; the build
 * never rasterises anything. Each sprite is INKCELL_EMOJI_SIZE square, a palette index and an
 * opacity per pixel, run-length encoded - emoji are mostly flat fills inside a transparent
 * margin, so the runs cost a fraction of the raw pixels.
 *
 * The size is set by the largest place a sprite is drawn, not the most common. A sprite in a
 * line of text is a cell of fifteen to twenty pixels and a keycap on the emoji keyboard is four
 * times that, and a sprite stored for the cell was a sprite blown up into a grid of visible
 * squares on the key. Stored at 32 it is scaled *down* into a line of text, which is the
 * direction that loses nothing, and up by only two into a key, which a smooth filter carries.
 *
 * The opacity is what makes both of those smooth. A sprite cut at one alpha threshold has a
 * staircase for an outline, and no filter can recover the edge that was thrown away; eight
 * levels of it kept is an outline that blends into whatever it is drawn over.
 */

#define INKCELL_EMOJI_SIZE 32

/* Index 0 means transparent; a stored index N is palette entry N - 1. */
#define INKCELL_EMOJI_TRANSPARENT 0

struct inkcell_emoji_single {
    uint32_t codepoint;
    uint16_t sprite;
};

struct inkcell_emoji_sequence {
    uint32_t first; /* leading codepoint, the key this table is sorted on */
    uint16_t tail;  /* offset into sequence_tail of the codepoints after the first */
    uint8_t length; /* codepoints in the whole sequence, including the first */
    uint16_t sprite;
};

struct inkcell_emoji_table {
    const uint8_t (*palette)[3];
    uint16_t palette_size;
    /* Flat (head, index) pairs; run N is runs[N * 2] and runs[N * 2 + 1]. The head is the
       opacity level in its top three bits and the run length less one in its bottom five. */
    const uint8_t *runs;
    const uint32_t *run_offsets;
    const struct inkcell_emoji_single *singles;
    uint32_t single_count;
    const struct inkcell_emoji_sequence *sequences;
    uint32_t sequence_count;
    const uint32_t *sequence_tail;
    uint8_t longest_sequence;
};

extern const struct inkcell_emoji_table inkcell_emoji_table;

/*
 * Longest emoji starting at codepoints[0]. Returns how many codepoints it consumed - 0 when
 * none of them start an emoji - and stores the sprite id in *sprite.
 *
 * Greedy on purpose: a regional-indicator pair is a flag rather than two letters, and a ZWJ
 * sequence is one glyph rather than its parts, so the longest match is the right one.
 */
size_t inkcell_emoji_match(const uint32_t *codepoints, size_t count, uint16_t *sprite);

/* Expand `sprite` into one palette index per pixel, row by row. Index 0 is transparent.
   Callers decode once and then index, rather than walking the runs per pixel. */
void inkcell_emoji_decode(uint16_t sprite, uint8_t out[INKCELL_EMOJI_SIZE * INKCELL_EMOJI_SIZE]);

/* The same, with each pixel's opacity beside its index: 0 wherever the index is transparent,
   and otherwise one of eight steps up to 255. `alpha` may be NULL, which is decode() above. */
void inkcell_emoji_decode_alpha(uint16_t sprite,
                                uint8_t index[INKCELL_EMOJI_SIZE * INKCELL_EMOJI_SIZE],
                                uint8_t alpha[INKCELL_EMOJI_SIZE * INKCELL_EMOJI_SIZE]);

/* Colour behind a decoded index. Returns false for the transparent index. */
bool inkcell_emoji_color(uint8_t index, uint8_t rgb[3]);

/* Codepoints that attach to the character before them and never take a cell of their own:
   variation selectors, skin-tone modifiers, the zero-width joiner, combining marks. Absorbing
   these is what stops an emoji written as base plus modifier - the common spelling, and the
   only spelling for things like U+26F0 U+FE0F - from drawing as two cells. */
bool inkcell_emoji_is_zero_width(uint32_t codepoint);

/*
 * One drawable cell of a UTF-8 string.
 *
 * A cell is not a byte and not always a codepoint: a flag is a pair of regional indicators, a
 * family is a ZWJ sequence, and a modifier attaches to whatever came before it. Layout and
 * drawing both walk cells, through the same function, so a line always measures as wide as it
 * draws.
 */
struct inkcell_text_cell {
    size_t bytes; /* source bytes consumed; 0 at the end of the string */
    bool is_emoji;
    uint16_t sprite;    /* when is_emoji */
    uint32_t codepoint; /* when not */
};

struct inkcell_text_cell inkcell_text_cell_next(const char *text);

/* Cells a string occupies once drawn. */
size_t inkcell_text_cells(const char *text);

/* Byte offset of cell `index`, or of the NUL when the string is shorter. */
size_t inkcell_text_cell_offset(const char *text, size_t index);

/* Truncate in place to at most `cells` cells, never inside one. */
void inkcell_text_cell_truncate(char *text, size_t cells);

#ifdef __cplusplus
}
#endif

#endif /* INKCELL_EMOJI_H */
