#ifndef INKCELL_ICON_H
#define INKCELL_ICON_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Monochrome icon sprites, drawn in whatever colour the theme says.
 *
 * The UI used to mark every row with a character: "> " for a row that opens something, "* " for
 * an unsaved edit, "#" for a channel, "+" for a new message, "*" for the connected device. They
 * are readable once somebody has learnt them and invisible until then, they cost a text column
 * each, and they cannot say anything a keyboard cannot type. An icon in the same slot is read
 * without being learnt, which is why every phone and desktop platform puts one there.
 *
 * These are *not* emoji, and the difference is the whole point of a second sprite table:
 *
 *   - An emoji carries its own colours (include/inkcell/ui/emoji.h) - the red of a flag is most of
 *     what makes it recognisable at 20 px. An icon carries coverage only, and takes the ink of
 *     whatever it is standing in for: a chevron on a selected row is the selected row's colour,
 *     an unsaved dot is the accent, a warning is the bad tone. It is themed like text, because
 *     it is doing text's job.
 *   - An emoji is looked up by codepoint, because it arrives inside a name somebody typed. An
 *     icon is named by the UI (INKCELL_ICON_CHEVRON), because it is chosen by a renderer.
 *
 * Coverage is 4 bits per pixel - 0 is nothing, 15 is solid - which is what lets a sprite be
 * resampled into a cell of any size without the stepped edges a 1-bit mask would give. The
 * sprites are 32 px square, comfortably above the 24 px cell they usually land in and still
 * sharp at the several-times-body-text size an empty screen draws one at; the whole set is
 * about 15 KB. The data is generated by scripts/gen-icons.py from Material Symbols Rounded and
 * committed, so the build rasterises nothing and never reaches the network; the catalog it is
 * generated from is include/inkcell/ui/icons.def.
 */

#define INKCELL_ICON_SIZE 32
#define INKCELL_ICON_MAX_ALPHA 15

/*
 * What a sprite is a picture *of*, in Material's own grid units - which is what a renderer needs
 * to turn "this icon is 32 px of data" into "this icon should be drawn this big".
 *
 * Material draws a symbol on a 24 square and keeps it inside the central 20, so the 20 is the
 * part that carries the shape and the ring around it is air by design. A sprite holds a little
 * more than the 24 - INKCELL_ICON_WINDOW - because at the fill and weight these are rasterised
 * at, the full-bleed symbols (`hub`, the antenna, the warning triangle) reach the grid's edge and
 * a hair past it; a window that cuts one cuts it on every screen it appears on.
 *
 * So a renderer that wants a symbol to stand as tall as some measurement - the capitals beside
 * it, say - scales that measurement by WINDOW / BODY to get the box to draw the whole sprite in.
 * The air comes out where air belongs, around the outside.
 */
#define INKCELL_ICON_WINDOW 256
#define INKCELL_ICON_BODY 200

/*
 * Every icon this build can draw.
 *
 * INKCELL_ICON_NONE is 0 and draws nothing, which is what makes an icon slot safe to leave
 * zeroed: a widget's leading slot is declared once for a whole list and the rows that have
 * nothing to put in it say so by saying nothing.
 *
 * These are the ones inkcell itself draws. An application's own continue from
 * INKCELL_ICON_COUNT - see inkcell_icon_set_app_table() at the bottom of this file.
 */
enum inkcell_icon {
    INKCELL_ICON_NONE = 0,
#define INKCELL_ICON_ENTRY(id, glyph) INKCELL_ICON_##id,
#include "inkcell/ui/icons.def"
#undef INKCELL_ICON_ENTRY
    INKCELL_ICON_COUNT
};

/*
 * Sprite data, in the shape emoji.h uses for the same reason: flat runs, so a sprite that is
 * mostly one value costs a handful of bytes rather than 256.
 *
 * Runs are (count, alpha) pairs; icon N's runs are [run_offsets[N], run_offsets[N + 1]). Each
 * icon's runs cover exactly INKCELL_ICON_SIZE * INKCELL_ICON_SIZE pixels, row by row.
 */
struct inkcell_icon_table {
    const uint8_t *runs;
    const uint32_t *run_offsets; /* INKCELL_ICON_COUNT + 1 entries */
};

extern const struct inkcell_icon_table inkcell_icon_table;

/*
 * Expand `icon` into one coverage value per pixel, row by row, 0 to INKCELL_ICON_MAX_ALPHA.
 *
 * Decoded once and then sampled, rather than the runs being walked per pixel. An unknown icon
 * - and INKCELL_ICON_NONE - fills `out` with zeroes, so a caller never has to test first.
 */
void inkcell_icon_alpha(enum inkcell_icon icon, uint8_t out[INKCELL_ICON_SIZE * INKCELL_ICON_SIZE]);

/*
 * The glyph name behind an icon: "chevron_right", "link_off".
 *
 * Diagnostics, tests and the generator, never a screen - it names a shape in a font rather than
 * anything a person reads, which is why it is not in the string catalog. Empty for
 * INKCELL_ICON_NONE and for an id out of range.
 */
const char *inkcell_icon_name(enum inkcell_icon icon);

/* Whether `icon` names something this build can draw. INKCELL_ICON_NONE is not one: it is the
   absence of an icon, which is legal everywhere and drawable nowhere. An application's own id
   counts, once its table is registered below. */
bool inkcell_icon_is_valid(enum inkcell_icon icon);

/* ---- an application's own icons -------------------------------------------------------------
 *
 * The icons above are inkcell's: the ones a *widget* reaches for - a chevron on a row that
 * opens something, a check on a chosen one, the warning triangle a dialog draws itself. What an
 * application's screens point at is the application's vocabulary, and a toolkit that shipped
 * `album` and `shuffle` would be a toolkit for one program.
 *
 * So an application brings its own sprite table and its ids continue inkcell's, exactly the way
 * its strings continue inkcell's catalog - see inkcell_i18n_set_catalog(). The ids are constants
 * of `enum inkcell_icon` rather than a second enum type, because there is one id space here and
 * a widget's `enum inkcell_icon` parameter has to accept both halves without a cast at every
 * call site:
 *
 *     enum {
 *         MYAPP_ICON__BASE = INKCELL_ICON_COUNT - 1,
 *     #define MYAPP_ICON_ENTRY(id, glyph) MYAPP_ICON_##id,
 *     #include "myapp/ui/icons.def"
 *     #undef MYAPP_ICON_ENTRY
 *         MYAPP_ICON_COUNT
 *     };
 *
 * Unlike the string catalog, the table registered here holds the application's icons *alone*
 * rather than both halves. A string table is an array of pointers an application builds by
 * including two .def files, which costs it nothing; a sprite table is generated binary data, and
 * asking an application to regenerate inkcell's seventy sprites into its own file would duplicate
 * 15 KB in the binary to save one comparison per lookup. So the lookup branches instead.
 *
 * Generate the table with inkcell's own scripts/gen-icons.py, pointed at the application's .def:
 *
 *     gen-icons.py <font> <out.c> --def include/myapp/ui/icons.def \
 *                  --macro MYAPP_ICON_ENTRY --symbol myapp_icon_table
 */
struct inkcell_icon_app_table {
    /* How many icons the application adds - MYAPP_ICON_COUNT - INKCELL_ICON_COUNT. */
    size_t count;
    const uint8_t *runs;
    const uint32_t *run_offsets; /* `count` + 1 entries, indexed from the application's first id */
    /* The glyph names, `count` entries, for the same diagnostics inkcell_icon_name() serves.
       May be NULL, which leaves an application's icons unnamed. */
    const char *const *names;
};

/*
 * Installs the application's icons. Call once, before anything draws.
 *
 * The structure and everything it points at must outlive the process - this is a generated
 * static table, not something to build on a stack. Passing NULL removes one, which leaves
 * inkcell's own icons as all there are: what a test, a capture harness or the library on its
 * own runs with.
 */
void inkcell_icon_set_app_table(const struct inkcell_icon_app_table *table);

/* How many ids are drawable in total - INKCELL_ICON_COUNT when no application table was
   registered, and INKCELL_ICON_COUNT + the table's `count` when one was. */
size_t inkcell_icon_count(void);

#ifdef __cplusplus
}
#endif

#endif /* INKCELL_ICON_H */
